{
 "title": "Gráficos Básicos",
 "tags": [
  "speedtest",
  "ping",
  "sistema"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uso de RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Temperatura CPU 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Temperatura CPU 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "{sensor=\"temp1\"}",
     "legendFormat": "{{node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\", instance=\"nodeexp:9100\", job=\"nodeexp\", sensor=\"temp0\"}}Temperatura"
    }
   ]
  },
  {
   "title": "Temperatura CPU 1",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{sensor=\"temp1\"}"
    }
   ]
  },
  { "title": "Temperatura CPU 0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperatura CPU 0",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "{sensor=\"temp0\"}",
     "legendFormat": "{{node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\", instance=\"nodeexp:9100\", job=\"nodeexp\", sensor=\"temp0\"}}Temperatura"
    }
   ]
  },
  {
   "title": "Temperatura CPU 0",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{sensor=\"temp0\"}"
    }
   ]
  },
  { "title": "Internet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Speedtest Ping",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Speedtest Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}